// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Biblioteca.Entities.Entities
{
    public partial class PantallasPorRol
    {
        public int Id { get; set; }
        public int RolId { get; set; }
        public int PantallaId { get; set; }
        public bool? Estado { get; set; }

        public virtual Pantallas Pantalla { get; set; }
        public virtual Roles Rol { get; set; }
    }
}