// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Biblioteca.Entities.Entities
{
    public partial class Pantallas
    {
        public Pantallas()
        {
            PantallasPorRol = new HashSet<PantallasPorRol>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Url { get; set; }
        public string Menu { get; set; }
        public string Icono { get; set; }
        public bool? Estado { get; set; }

        public virtual ICollection<PantallasPorRol> PantallasPorRol { get; set; }
    }
}