// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Biblioteca.Entities.Entities
{
    public partial class Roles
    {
        public Roles()
        {
            PantallasPorRol = new HashSet<PantallasPorRol>();
            Usuarios = new HashSet<Usuarios>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public bool? Habilitado { get; set; }
        public bool? Estado { get; set; }

        public virtual ICollection<PantallasPorRol> PantallasPorRol { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}