// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Biblioteca.Entities.Entities
{
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public bool? EsAdmin { get; set; }
        public int? RolId { get; set; }
        public string UrlFoto { get; set; }
        public bool? Estado { get; set; }

        public virtual Roles Rol { get; set; }
    }
}